### ISSUE TITLE
Defect: Unable to configure samples by clicking pencil icon

### ISSUE THREAD

**Issue by suzzopher** [littlerobot/slims#66]
When you select a sample and then click either the edit pencil icon the page will stop responding, you have to refresh the page to be able to use it again.

Steps to reproduce:
* Open a folder and Dewer > Cassette > Goblet > Wedge 1
* Select a sample
* Click the edit pencil
* Observe the page will stop responding

**Comment by StuBez** [comment]
I had this problem before but then stopped being able to reproduce it. It seems to be caused by a Javascript error.

<img width="1440" alt="screen shot 2015-09-09 at 10 20 25" src="https://cloud.githubusercontent.com/assets/910068/9758119/7603e8a6-56dc-11e5-8a2b-63406446358d.png">

@chuckn0rris Could the pencil icon only be enabled if the "Configure samples" process has been completed?

**Comment by chuckn0rris** [comment]
@suzzopher can't reproduce this bug.
@StuBez I think it is not necessary. Because we only can change 'Colour' attribute there.

**Comment by StuBez** [comment]
I can reproduce it on https://slims.dev/app_dev.php and http://slims.littlerobot.io

Clicking the edit button displays a dialog that allows editing any attribute, as well as the colour.

I have uploaded a video to https://www.dropbox.com/s/wnn897354awcsia/Edit%20sample%20bug.mov?dl=0

**Comment by chuckn0rris** [comment]
@StuBez got it, I thought it is about container edit window.

**Comment by suzzopher** [comment]
@StuBez @chuckn0rris This is still happening for me, what was the verdict on behaviour?

**Comment by StuBez** [comment]
@suzzopher It's possible I hadn't deployed it. Could I get you to check again when you have a moment. I believe the pencil should not be enabled initially but @chuckn0rris can confirm.

**Comment by suzzopher** [comment]
Excellent, the pencil is now greyed out.

**Comment by suzzopher** [comment]
Cool no longer an issue
