### ISSUE TITLE
Remove samples

### ISSUE THREAD

**Issue by StuBez** [littlerobot/slims#71]
# User interface
### Removing samples
- Checkboxes at beginning of each search result row to allow users to select samples to remove.
- A button to display a dialog box to enter details for the remove instance attributes.
  - There could be samples for different instance templates in the search results. Can we prevent the user from selecting samples with different templates?
  - Only needs to display the remove instance attribute fields - the type template and instance template was chosen when the sample was stored so we don't need to ask the user for this information.
  - There will not be a sample colour so this does not need to be on the dialog.
  - It would be helpful if there was some way for users to be able to edit information for individual samples, like they can after the store samples wizard has been completed. How much work would it be to allow this?
### Searching for samples
- Radio buttons to allow users to search for samples that have been stored or removed. Maybe something like **State:** () Stored (.) Removed
  - This will add another query parameter to the existing API request.
- As well as current information, display the remove instance answers in the table, if they are set for any samples in the results.
  - Any samples that have a state of "stored" will only have the values you are already displaying in the table. Samples with a state of "removed" will have those values and the extra ones that were added when the sample was removed.
# API
## Sample search
- Allow state to be specified - either "stored" or "removed".
## Container view
- Only return samples that have a state of "stored" in the API.
## Remove sample API
- I will specify the structure later but I think it will be similar to the store samples API but with less attributes.

**Comment by chuckn0rris** [comment]
@StuBez 
I think we should change our search tab a little bit. 
If we want edit (remove) samples right in that grid, I think the best way will be to change work flow a little. I am about change Search tab to Samples tab. Samples tab will have a grid with pagination plugin (30 record per 1 loading for example) and full list of samples. Also we will have instruments for sorting and filtering (instead of searching). So, we can sort samples by Sample Type, filter by added today, select items and press Remove. It almost all te same as you described but should be better than do this in search results grid, what do you think?

**Comment by StuBez** [comment]
Would you be able to able to make a screenshot of your idea?

The user will have to add information for several new attributes - the data they already entered when the sample was stored will stay the same.

The number of fields for them to fill in will usually be 4-10, I think.
